### ISSUE TITLE
ability to generate Windows Desktop + ANGLE + x64 configuration

### ISSUE THREAD

**Issue by richardeakin** [cinder/TinderBox#22]
Currently you can select these options, but the generated configuration + target (example Debug_ANGLE, Platform = x64) still ends up building for Win32. I believe it is because there is no ' "Debug_ANGLE|x64" node in the [vcxproj template](https://github.com/cinder/Cinder/blob/master/blocks/__AppTemplates/__Foundation/vc2013/foundation.vcxproj). This configuration does currently work if you add it manually (by copying a Debug_Angle configuration for Platform Win32 to x64).

Use case: If you were to make an app for the Windows Store, you would need to target 64bit, and use ANGLE, though you'd likely do your day to day dev on desktop. In order to keep things very similar as far as backend there, you can use ANGLE and desktop, so that you didn't incorrectly use something like compute shaders, etc., or some other unsupported feature.

**Comment by andrewfb** [comment]
Fixed now
