### ISSUE TITLE
Add support for generating VS 2015 projects

### ISSUE THREAD

**Issue by richardeakin** [cinder/TinderBox#6]
Even if we're not yet shipping VS 2015 projects, might as well add the option to generate them. Should be as easy as starting with the VS 2013 project templates and changing the version string, placing the output in a folder called vc2015.

[This dude](https://github.com/Hurleyworks/ciProjMgr) wrote his own application to do this..

**Comment by andrewfb** [comment]
The code in this repo already does this for WinRT projects, but it's not in the binaries we're distributing yet. The change is a little more work if we want to generate both 2013 and 2015 projects, but wouldn't be too bad. Bigger question is how long we intend to maintain 2013 support for Cinder itself.

**Comment by richardeakin** [comment]
This is outdated, VS 2015 is supported since last release.
